name: MagnetRemote
options:
  bundleIdPrefix: com.magnetremote
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
  DEVELOPMENT_TEAM: ""

targets:
  MagnetRemote:
    type: application
    platform: macOS
    sources:
      - path: MagnetRemote
        excludes:
          - "**/.DS_Store"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.magnetremote.app
      INFOPLIST_FILE: MagnetRemote/Info.plist
      CODE_SIGN_ENTITLEMENTS: MagnetRemote/MagnetRemote.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      COMBINE_HIDPI_IMAGES: YES
      ENABLE_HARDENED_RUNTIME: YES
      CODE_SIGN_STYLE: Automatic
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "13.0"
    entitlements:
      path: MagnetRemote/MagnetRemote.entitlements
